<?xml version="1.0" encoding="utf-8"?><Database Name="Blog" Class="dbBlogDataContextDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=MaiTuan;Initial Catalog=Blog;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="BlogConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ADMIN" Member="ADMINs">
    <Type Name="ADMIN">
      <Column Name="MAADMIN" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENTAIKHOAN" Type="System.String" DbType="Char(30)" CanBeNull="true" />
      <Column Name="MATKHAU" Type="System.String" DbType="Char(30)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CHUDE" Member="CHUDEs">
    <Type Name="CHUDE">
      <Column Name="MACHUDE" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENCHUDE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="CHUDE_TIN" Member="TINs" ThisKey="MACHUDE" OtherKey="MACHUDE" Type="TIN" />
    </Type>
  </Table>
  <Table Name="dbo.TACGIA" Member="TACGIAs">
    <Type Name="TACGIA">
      <Column Name="MATACGIA" Type="System.String" DbType="Char(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENTAGIA" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="TACGIA_TIN" Member="TINs" ThisKey="MATACGIA" OtherKey="MATACGIA" Type="TIN" />
    </Type>
  </Table>
  <Table Name="dbo.TIN" Member="TINs">
    <Type Name="TIN">
      <Column Name="MATIN" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENTIN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MOTA" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NGAYDANG" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MATACGIA" Type="System.String" DbType="Char(30)" CanBeNull="true" />
      <Column Name="MACHUDE" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Association Name="CHUDE_TIN" Member="CHUDE" ThisKey="MACHUDE" OtherKey="MACHUDE" Type="CHUDE" IsForeignKey="true" />
      <Association Name="TACGIA_TIN" Member="TACGIA" ThisKey="MATACGIA" OtherKey="MATACGIA" Type="TACGIA" IsForeignKey="true" />
    </Type>
  </Table>
</Database>